version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    platform: linux/amd64
    container_name: chatbot-backend
    ports:
      - "8000:8000"
    volumes:
      - ./templates:/app/templates  # mount thư mục template bên ngoài
      - ./data:/app/data
    env_file: .env 
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: chatbot-frontend
    ports:
      - "8501:8501"
    env_file: .env 
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - backend
  

  