apiVersion: v1
kind: Service
metadata:
  name: chatbot-backend
spec:
  type: LoadBalancer
  selector:
    app: chatbot-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  sessionAffinity: ClientIP  # Sticky session
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours