# -----------------------------------------------------------------------------
# CONFIGMAPS
# -----------------------------------------------------------------------------

apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-backend-config
  namespace: default
  labels:
    env: prod
data:
  APP_ENV: "${APP_ENV}"
  DATABASE: "${DATABASE}"
  LOG_LEVEL: "${LOG_LEVEL}"
  LOG_DIR: "${LOG_DIR}"
  LLM_MODEL: "${LLM_MODEL}"
  TTS_MODEL: "${TTS_MODEL}"
  TTS_SPEAKER_ID: "${TTS_SPEAKER_ID}"
  TTS_SPEED: "${TTS_SPEED}"
  TTS_ENCODE_TYPE: "${TTS_ENCODE_TYPE}"
  GEMINI_TTS_VOICE_LANGUAGE_CODE: "${GEMINI_TTS_VOICE_LANGUAGE_CODE}"
  GEMINI_TTS_VOICE_NAME: "${GEMINI_TTS_VOICE_NAME}"
  GEMINI_TTS_AUDIO_ENCODING: "${GEMINI_TTS_AUDIO_ENCODING}"
  GEMINI_TTS_SPEAKING_RATE: "${GEMINI_TTS_SPEAKING_RATE}"
  GEMINI_TTS_PITCH: "${GEMINI_TTS_PITCH}"
  GEMINI_TTS_SAMPLE_RATE_HERTZ: "${GEMINI_TTS_SAMPLE_RATE_HERTZ}"
  EMBEDDING_MAX_TOKENS: "${EMBEDDING_MAX_TOKENS}"
  S3_PATH: "${S3_PATH}"
  S3_ENDPOINT_URL: "${S3_ENDPOINT_URL}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-frontend-config
  namespace: default
  labels:
    env: prod
data:
  API_BASE_URL: "http://chatbot-backend:8000/api"  # Service DNS name in K8s

# -----------------------------------------------------------------------------
# SECRETS
# -----------------------------------------------------------------------------

---
apiVersion: v1
kind: Secret
metadata:
  name: chatbot-backend-secret
  namespace: default
  labels:
    env: prod
type: Opaque
stringData: # Use stringData instead of data to avoid base64 encoding
  DATABASE_URL: "${DATABASE_URL}"
  OPENSEARCH_URL: "${OPENSEARCH_URL}"
  LLM_API_URL: "${LLM_API_URL}"
  LLM_API_KEY: "${LLM_API_KEY}"
  TTS_API_URL: "${TTS_API_URL}"
  TTS_API_KEY: "${TTS_API_KEY}"
  GEMINI_TTS_API_URL: "${GEMINI_TTS_API_URL}"
  GEMINI_TTS_API_KEY: "${GEMINI_TTS_API_KEY}"
  EMBEDDING_API_URL: "${EMBEDDING_API_URL}"
  EMBEDDING_API_KEY: "${EMBEDDING_API_KEY}"
  EMBEDDING_MODEL_NAME: "${EMBEDDING_MODEL_NAME}"
  HF_TOKEN: "${HF_TOKEN}"
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"