# =============================================================================
# VNG CHATBOT - KUBERNETES DEPLOYMENT
# =============================================================================

# -----------------------------------------------------------------------------
# DEPLOYMENTS
# -----------------------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-backend
  template:
    metadata:
      labels:
        app: chatbot-backend
    spec:
      containers:
        - name: backend
          image: vcr.vngcloud.vn/60108-chatbot-rag/chatbot-rag-template-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: chatbot-backend-config
            - secretRef:
                name: chatbot-backend-secret
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          volumeMounts:
            - name: logs
              mountPath: /app/logs
            - name: templates
              mountPath: /app/templates
            - name: data
              mountPath: /app/data
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8000
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8000
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
      volumes:
        - name: logs
          emptyDir: {}
        - name: templates
          configMap:
            name: templates-config
        - name: data
          configMap:
            name: data-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-frontend
  template:
    metadata:
      labels:
        app: chatbot-frontend
    spec:
      containers:
        - name: frontend
          image: vcr.vngcloud.vn/60108-chatbot-rag/chatbot-rag-template-frontend:latest 
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          envFrom:
            - configMapRef:
                name: chatbot-frontend-config
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 5
            periodSeconds: 5

# -----------------------------------------------------------------------------
# SERVICES
# -----------------------------------------------------------------------------

---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-backend
spec:
  type: LoadBalancer
  selector:
    app: chatbot-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  sessionAffinity: ClientIP  # Sticky session
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-frontend
spec:
  type: LoadBalancer
  selector:
    app: chatbot-frontend
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  sessionAffinity: ClientIP  # Sticky session
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours 