apiVersion: v1
kind: Service
metadata:
  name: trung-nguyen-frontend
spec:
  type: LoadBalancer
  selector:
    app: trung-nguyen-frontend
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  sessionAffinity: ClientIP  # Sticky session
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours