apiVersion: apps/v1
kind: Deployment
metadata:
  name: trung-nguyen-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trung-nguyen-frontend
  template:
    metadata:
      labels:
        app: trung-nguyen-frontend
    spec:
      containers:
        - name: frontend
          image: vcr.vngcloud.vn/60108-chatbot-rag/trung-nguyen-frontend:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          envFrom:
            - configMapRef:
                name: trung-nguyen-frontend-config
#            - secretRef:
#                name: trung-nguyen-frontend-secret
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 5
            periodSeconds: 5