apiVersion: v1
kind: Secret
metadata:
  name: chatbot-backend-secret
  namespace: default
  labels:
    env: prod
type: Opaque
stringData: # Use stringData instead of data to avoid base64 encoding
  DATABASE_URL: "postgresql://postgres:postgres123@postgres:5432/trung_nguyen_chatbot"
  OPENSEARCH_HOST: "your_opensearch_host"
  OPENSEARCH_PORT: "your_opensearch_port"
  OPENSEARCH_USER: "your_opensearch_user"
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: "your_opensearch_password"
  OPENSEARCH_URL: "your_opensearch_url"
  LLM_API_URL: "your_llm_api_url"  # Update
  LLM_API_KEY: "your_llm_api_key"  # Update
  TTS_API_URL: "your_tts_api_url"  # Update
  TTS_API_KEY: "your_tts_api_key"  # Update
  GEMINI_TTS_API_URL: "your_gemini_tts_api_url"
  GEMINI_TTS_API_KEY: "your_gemini_tts_api_key"
  EMBEDDING_API_URL: "your_embedding_api_url"  # Update
  EMBEDDING_API_KEY: "your_embedding_api_key"  # Update
  EMBEDDING_MODEL_NAME: "your_embedding_model_name"  # Update
  HF_TOKEN: "your_huggingface_token"  # Update
  AWS_ACCESS_KEY_ID: "your_aws_access_key_id"  # Update
  AWS_SECRET_ACCESS_KEY: "your_aws_secret_key_id"  # Update
