# =============================================================================
# TRUNG NGUYEN CHATBOT - KUBERNETES DEPLOYMENT
# =============================================================================

# -----------------------------------------------------------------------------
# CONFIGMAPS
# -----------------------------------------------------------------------------

apiVersion: v1
kind: ConfigMap
metadata:
  name: trung-nguyen-backend-config
  namespace: default
  labels:
    env: prod
data:
  APP_ENV: "prod"
  LOG_LEVEL: "INFO"
  LLM_MODEL: "gemini-2.5-flash"
  TTS_MODEL: "zalo-tts-vi"
  TTS_SPEAKER_ID: "1"
  TTS_SPEED: "1.0"
  TTS_ENCODE_TYPE: "1"
  EMBEDDING_MAX_TOKENS: "8190"
  LOG_DIR: "/app/logs"
  STORE_URL: "https://thiencaphe.trungnguyenlegendcafe.net/"
  PRODUCT_URL: "https://thiencaphe.trungnguyenlegendcafe.net/san-pham/"
  S3_PATH: "trung-nguyen-docs"  # Update with actual value
  S3_ENDPOINT_URL: "https://hcm04.vstorage.vngcloud.vn"  # Update with actual value
  S3_EXCEL_FILE_KEY: "trung-nguyen-legend.xlsx"  # Update with actual value
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trung-nguyen-frontend-config
  namespace: default
  labels:
    env: prod
data:
  API_BASE_URL: "http://trung-nguyen-backend:8000/api"  # Service DNS name in K8s

# -----------------------------------------------------------------------------
# SECRETS
# -----------------------------------------------------------------------------

---
apiVersion: v1
kind: Secret
metadata:
  name: trung-nguyen-backend-secret
  namespace: default
  labels:
    env: prod
type: Opaque
stringData: # Use stringData instead of data to avoid base64 encoding
  DATABASE_URL: "postgresql://postgres:postgres123@postgres:5432/trung_nguyen_chatbot"
  LLM_API_URL: "your_llm_api_url"  # Update
  LLM_API_KEY: "your_llm_api_key"  # Update
  TTS_API_URL: "your_tts_api_url"  # Update
  TTS_API_KEY: "your_tts_api_key"  # Update
  EMBEDDING_API_URL: "your_embedding_api_url"  # Update
  EMBEDDING_API_KEY: "your_embedding_api_key"  # Update
  EMBEDDING_MODEL_NAME: "your_embedding_model_name"  # Update
  HF_TOKEN: "your_huggingface_token"  # Update
  AWS_ACCESS_KEY_ID: "your_aws_access_key_id"  # Update
  AWS_SECRET_ACCESS_KEY: "your_aws_secret_key_id"  # Update

# -----------------------------------------------------------------------------
# DEPLOYMENTS
# -----------------------------------------------------------------------------

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trung-nguyen-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trung-nguyen-backend
  template:
    metadata:
      labels:
        app: trung-nguyen-backend
    spec:
      containers:
        - name: backend
          image: vcr.vngcloud.vn/60108-chatbot-rag/trung-nguyen-backend:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: trung-nguyen-backend-config
            - secretRef:
                name: trung-nguyen-backend-secret
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          volumeMounts:
            - name: logs
              mountPath: /app/logs
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: logs
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trung-nguyen-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trung-nguyen-frontend
  template:
    metadata:
      labels:
        app: trung-nguyen-frontend
    spec:
      containers:
        - name: frontend
          image: vcr.vngcloud.vn/60108-chatbot-rag/trung-nguyen-frontend:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          envFrom:
            - configMapRef:
                name: trung-nguyen-frontend-config
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 5
            periodSeconds: 5

# -----------------------------------------------------------------------------
# SERVICES
# -----------------------------------------------------------------------------

---
apiVersion: v1
kind: Service
metadata:
  name: trung-nguyen-backend
spec:
  type: LoadBalancer
  selector:
    app: trung-nguyen-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  sessionAffinity: ClientIP  # Sticky session
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours
---
apiVersion: v1
kind: Service
metadata:
  name: trung-nguyen-frontend
spec:
  type: LoadBalancer
  selector:
    app: trung-nguyen-frontend
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  sessionAffinity: ClientIP  # Sticky session
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800  # 3 hours 